name: "Unit Tests"
description: Run unit tests

inputs:
  test-scope:
    description: Specify the scope of tests to run (all or changed).
    required: true
    default: "all"

runs:
  using: composite
  steps:
    - name: Determine Test Scope
      shell: bash
      id: variables
      run: |
        echo "Selected test scope: ${{ inputs.test-scope }}"
        if [ "${{ inputs.test-scope }}" = "changed" ]; then
          echo "arg='--since'" >> $GITHUB_OUTPUT
        else
          echo "arg='--all'" >> $GITHUB_OUTPUT
    outputs:
      arg: ${{ steps.variables.outputs.arg }}

      - name: Run Unit Tests
        shell: bash
        run: yarn workspaces foreach ${{ steps.variables.outputs.arg }} --parallel run test
