name: 'Slack Notification'
description: 'Send notification to Slack channel'

inputs:
  channel-id:
    description: 'Slack channel ID'
    required: true
  message:
    description: 'Message to send'
    required: true
  bot-token:
    description: 'Slack bot token'
    required: true
    default: '${{ secrets.SLACK_BOT_TOKEN }}'

runs:
  using: "composite"
  steps:
    - name: Send Slack notification
      uses: slackapi/slack-github-action@v1.25.0
      with:
        channel-id: ${{ inputs.channel-id }}
        slack-message: ${{ inputs.message }}
      env:
        SLACK_BOT_TOKEN: ${{ inputs.bot-token }} 