name: Build Workflow

on:
  push:
    branches:
      - main
      - 'mx/release/**'
  pull_request:
    branches:
      - main
      - 'mx/release/**'
jobs:
  build:
    name: Build Widgets
    runs-on: self-hosted

    steps:
      - name: "Checking-out code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: "Setup Environment"
        uses: ./.github/actions/setup-environment

      - name: "Running build"
        uses: ./.github/actions/build-widgets
        with:
          mode: "build"
          build-scope: "changed"
