name: Build Workflow

on:
  push:
    branches:
      - main
      - 'mx/release/**'
  pull_request:
    branches:
      - main
      - 'mx/release/**'
jobs:
  build:
    name: Build Widgets
    runs-on: ubuntu-latest

    steps:
      - name: "Setup Environment"
        uses: ./.github/actions/setup-environment

      - name: "Running build"
        uses: ./.github/actions/build-widgets
        with:
          mode: "build"
          build-scope: "changed"
