name: Run release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Release
    runs-on: ubuntu-latest

    steps:
      - name: "Setup Environment"
        uses: ./.github/actions/setup-environment

      - name: "Running build"
        uses: ./.github/actions/build-widgets
        with:
          mode: "release"
          build-scope: "changed"
