name: Run Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Release
    runs-on: ubuntu-latest

    steps:
      - name: "Checking-out code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: "Setup Environment"
        uses: ./.github/actions/setup-environment

      - name: "Running build"
        uses: ./.github/actions/build-widgets
        with:
          mode: "release"
          build-scope: "changed"
