name: Run unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-latest

    steps:
      - name: "Setup Environment"
        uses: ./.github/actions/setup-environment

      - name: "Running unit tests"
        uses: ./.github/actions/unit-tests
        with:
          test-scope: "changed"
